// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1611151151);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1611151123);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 11360);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "[\"DuckDuckGo Lite\",\"Searx\",\"StartPage\",\"Jive Search\",\"Qwant\",\"MetaGer\",\"Invidious\"]");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.cdn.mozilla.net/user-media/addons/607454/ublock_origin-1.29.2-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.region.update.first-seen", 1611151124);
user_pref("browser.region.update.region", "NL");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.slowStartup.averageTime", 2193);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.lastColdStartupCheck", 1611151122);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"home-button\",\"downloads-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"add-ons-button\",\"preferences-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "80.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.LibreWolf.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "80.0.1");
user_pref("extensions.lastPlatformVersion", "80.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bee52337-c679-4bd4-a15d-35da2e4d6b9a\",\"screenshots@mozilla.org\":\"f2b94649-c3d5-4932-80b1-f84ee3fe0e75\",\"default-theme@mozilla.org\":\"e3c673ae-8aa1-4713-8d63-6cd807e0ccb6\",\"google@search.mozilla.org\":\"2970e7fd-45c8-4528-a4b8-6d419803a7af\",\"amazondotcom@search.mozilla.org\":\"702060fd-a393-45f7-bbfd-b14032117dae\",\"wikipedia@search.mozilla.org\":\"356d44fb-fd9b-4a47-ac82-40c865ffc511\",\"uBlock0@raymondhill.net\":\"631a4819-bc4e-4bb3-8511-bed56000fde5\",\"bing@search.mozilla.org\":\"c3f8fb3e-2071-4533-8d86-45a545b2e898\",\"ddg@search.mozilla.org\":\"260379e5-3aa4-4507-8e98-a50837621067\",\"ebay@search.mozilla.org\":\"65721af5-21e2-41f6-9b28-a07feb27c73c\"}");
user_pref("identity.sendtabpromo.url", "");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 2147483647);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "bf2be42b-c330-4414-82cf-581014785ed6");
user_pref("security.sandbox.plugin.tempDirSuffix", "f281b4f1-d716-48b5-9124-3e42a30f2698");
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.mobileAndroidURL", "");
user_pref("signon.management.page.mobileAppleURL", "");
user_pref("startup.homepage_override_url", "about:blank");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("toolkit.startup.last_success", 1611151120);
user_pref("toolkit.telemetry.cachedClientID", "f9e051ce-9ca6-4b81-ac0c-7b169c883e8e");
